### PR TITLE
Build directory

### PR DESCRIPTION
**Pull request by lianghai**
A new directory build-hindkit/ has been added to replace the old build/.
This is an FDK-based build directory with assistance from [Hindkit](https://github.com/itfoundry/hindkit).
Hindkit needs to be installed properly before running build.py.

### CODE REVIEW

**Comment by lianghai** [comment]
- A suffix "FDK" is added to the family name so it's convenient to compare these OTFs to the old ones and FontForge's. Feel free to remove the line `family.output_name_affix = '{} FDK'` from `build.py` when the suffix is not needed anymore.
- UFO masters were taken directly from `sources/`, then they passed Hindkit and FDK without hiccup.
- The main feature file got cleaned up a bit but I didn't rewrite it.
- `font.designspace` and `FontMenuNameDB` are actually generated automatically by `build.py`, and they're usually ignored by `.gitignore`. However since you guys are new to FDK, I keep them visible for now.
- An temporary directory `instances/` (just like the old `style/`) is generated during interpolating and compiling, but it's ignored by `.gitignore`.
- Style-linking is on, and the version 4 of `<OS/2>` table is used. All can be configured in `build.py` (`builder.set_options()`).
- Vertical metrics have been set according to the values in UFO masters and an additional 0.2 em line gap. See `<hhea>` and `<OS/2>` tables in `tables.fea` for more information.
- The `<name>` table has been configured mostly properly. Please review it. (Btw, is the original designer "Pushpananda Ekanayaka" or "Pushpananda Ekanayake" or "Pushpananda Ekanayakes"? At least three versions of his name appeared in the repo.)
- The `<GPOS>` table was polluted by the useless kerning lookup. Will clean it up after the merge.

**Comment by lianghai** [comment]
Btw, the version number (`head.FontRevision`) is now controled in `build.py`.
This build was prepared with a version number of "0.100", which might have problem installing in Windows because it's less than 1.000.

**Comment by paarandika** [comment]
```Traceback (most recent call last):
  File "E:\cheena\abhaya-libre-font\build-hindkit\build.py", line 3, in <module>
    import hindkit as kit
  File "C:\Python27\lib\site-packages\hindkit-0.1.4-py2.7.egg\hindkit\__init__.py", line 5, in <module>
    from hindkit.constants import paths, linguistics, styles, templates
ImportError: No module named constants```
Gives this error after running the build.py in AbhayaLibre hindkit build.(I have installed hindkit from git repo master)

**Comment by lianghai** [comment]
Ah! Sorry for this. I didn't add those subpackages to `setup.py`. Now it's fixed in Hindkit.
However, I've noticed you're working on Windows. This is the real problem... Hindkit is developed on Mac, and I don't have any knowledge of how it could be ported to Windows... (Mostly it's about those `subprocess`-related code, I guess.)

**Comment by pathumego** [comment]
@lianghai A question, If I set UPM to 1000 and change the values of `TypoAscender` and `TypoDescender`, how is `  winAscent` and `winDescent` calculated? your comment says ` 1024 * (0.2 + 0.2/2)` this based on the values from UFO?

**Comment by lianghai** [comment]
Uh, those are just temporary values I set because I couldn't find reliable values in your old files...
You should refer to https://github.com/googlefonts/gf-docs/blob/master/VerticalMetricsRecommendations.md to set proper values.

**Comment by lianghai** [comment]
Those are temporary values I set because I couldn't find reliable values in your old files.
To set them properly, you should refer to https://github.com/googlefonts/gf-docs/blob/master/VerticalMetricsRecommendations.md

**Pull request merged**
